name: continue-on-error
on: 
  push:
  workflow_dispatch:
jobs:
  ignore:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        continue-on-error: true
        run: exit 1
      - run: echo "I don't care!"
      - run: echo "I too will run!!!!"
      - id: step2
        run: exit 1
      - run: echo "I think I too will run!!!!!!"
       
