# This is a basic workflow to help you get started with Actions

name: Env Test1

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  env-test1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Basic variable usage
       run: |
         echo Let\'s define a variable:
         VERSION_PREFIX=V1.0.

         echo Display the version prefix: $VERSION_PREFIX
         echo And use it multiple times: $VERSION_PREFIX
          
      
