name: State validations
on: 
  push:
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - id: generator
        run: if [[ $((RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi
      - if: ${{ always() }}
        run: echo ${{ steps.generator.outcome }}
